<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action'=>'Действия',
    'address' => 'Адрес',
    'answer' => 'Ответь',
    'answers' => 'Ответы',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот запись?',
    'article' => 'статья',
    'articles' => 'Статьи',
    'author' => 'Автор',

    'birthplace' => 'Место рождения',
    'btn-create' => '<i class="fa fa-plus"></i> Добавить',
    'btn-delete' => '<i class="fa fa-trash-o"></i> Удалить',
    'btn-exam' => '<i class="fa fa-question-circle"></i> Тест',
    'btn-next' => '<i class="fa fa-play-circle"></i> Следующий',
    'btn-save' => '<i class="fa fa-floppy-o"></i> Сохранить',
    'btn-sign-in' => 'Вход',
    'btn-sign-out' => 'Выход',
    'btn-update' => '<i class="fa fa-pencil"></i> Обновить',

    'btn-question' => '<i class="fa fa-question"></i> Вопросы',
    'btn-rate' => '<i class="fa fa-pencil-square"></i> Оценка',
    'btn-search' => '<i class="fa fa-binoculars"></i> Найти',
    'btn-add' => '<i class="fa fa-plus-circle"></i> Добавить',
    'behaviors' => 'Дополнительно',


    'comment' => 'Комментария',
    'confirm' => 'Подтверждать',
    'confirm-delete' => 'Вы действительно хотите удалить эту запись',
    'contact' => 'Контакт',
    'course' => 'Курс',
    'courses' => 'Курсы',
    'Create' => 'Новый',
    'created_at' => 'Время создания',
    'created_by' => 'Последнее обновление:',

    'date' => 'Дата',
    'Delete' => 'Удалить',
    'description' => 'Описание',
    'details' => 'Детали',
    'difficulty' => 'Уровень',

    'exam' => 'Экзамен',
    'email' => 'Электронная почта',

    'faculty' => 'Факультет',
    'finished_at' => 'Закончил',
    'forbidden' => 'У вас недостаточно прав для этого действия !!!',
    'fullname' => 'ФИО',

    'gruppa' => 'Группа',

    'home' => 'Главная страница',

    'id' => '№',
    'is_correct' => 'Правильный',
    'lang' => 'язык',
    'lecture' => 'Лекция',
    'resource' => 'Литературы',
    'resource-files' => 'Литературы с вложениям',

    'media' => 'Мулти медиа',
    'multianswer' => 'мульти ответ',

    'name' => 'имя',
    'not-enough' => 'мало информации',
    'not-found' => 'Данные не найдены',

    'password' => 'Пароль',
    'phone' => 'Телефон',
    'placeholder-address' => 'Манзилни киритинг',
    'placeholder-birthplace' => 'Введите адрес',
    'placeholder-course' => 'Введите курс',
    'placeholder-email' => 'Введите адрес электронной почты',
    'placeholder-fullname' => 'Введите ФИО',
    'placeholder-gruppa' => 'Введите группу',
    'placeholder-password' => 'Введите пароль',
    'placeholder-phone' => 'Введите номер телефона',
    'placeholder-username' => 'Введите логин',

    'question' => 'Вопрос',
    'questions' => 'Вопросы теста',
    'essies' => 'Вопросы',
    'task' => 'Ситуационная задача',
    'tasks' => 'Ситуационные задачы',
    'total' => 'Всего',
    'test-summary' => 'Балл: <span class="label label-primary">{total}</span>  правыльный: <span class="label label-success">{success}</span>  неправыльный: <span class="label label-danger">{fail}</span>',

    'rating' => 'Оценка',
    'remember-me' => 'запомнить меня',
    'register' => 'Журнал',
    'Reset' => '',
    'resources' => 'Ресурсы',

    'Search' => 'Найти',
    'sequence' => 'Номер темы',
    'started_at' => 'время начала',
    'status' => 'Статус',
    'students' => 'Студенты',

    'test' => 'Результати теста',
    'time_difference' => 'Пройденное время',
    'title' => 'Заглавие',
    'type' => 'тип',

    'Update {modelClass}: ' => 'Обновить {modelClass}',
    'Update' => 'Обновить',
    'updated_at' => 'Обновлено',
    'user' => 'пользователь',
    'username' => 'Логин',
    'users' => 'пользователи',

    'subject' => 'Предмет',
    'short-name' => 'Короткое имя',
    'subjects' => 'Предметы',
    'kafedra' => 'Кафедра',
    'kafedras' => 'Кафедри',
    'Active' => 'Актив',
    'Not active' => 'Не актив',
    'kafedras and subjects' => 'Кафедри и Предметы',

];
