<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action'=>'Амаллар',
    'address' => 'Манзил',
    'answer' => 'Жавоб',
    'answers' => 'Жавоблар',
    'Are you sure you want to delete this item?' => 'Ушбу ёзувни ўчиришга аминмисиз?',
    'article' => 'дарс',
    'articles' => 'Дарслар',
    'author' => 'Муаллиф',

    'birthplace' => 'Туғилган манзил',
    'btn-create' => '<i class="fa fa-plus"></i> Қўшиш',
    'btn-delete' => '<i class="fa fa-trash-o"></i> Ўчириш',
    'btn-exam' => '<i class="fa fa-question-circle"></i> Тест',
    'btn-next' => '<i class="fa fa-play-circle"></i> Кейингиси',
    'btn-save' => '<i class="fa fa-floppy-o"></i> Сақлаш',
    'btn-sign-in' => 'Кириш',
    'btn-sign-out' => 'Чиқиш',
    'btn-update' => '<i class="fa fa-pencil"></i> Тахрирлаш',
    'btn-question' => '<i class="fa fa-question"></i> Саволлар',
    'btn-rate' => '<i class="fa fa-pencil-square"></i> Бахолаш',
    'btn-search' => '<i class="fa fa-binoculars"></i> Қидирув',
    'btn-add' => '<i class="fa fa-plus-circle"></i> Қўшиш',
    'behaviors' => 'Қўшимча',


    'comment' => 'Изох',
    'confirm' => 'Тасдиқ',
    'confirm-delete' => 'Ушбу ёзувни ўчиришга аминмисиз?',
    'contact' => 'Боғланиш',
    'course' => 'Курс',
    'courses' => 'Курслар',
    'Create' => 'Янги',
    'created_at' => 'Яратилган вақт',
    'created_by' => 'Томонидан яратилган ёки ўзгартирилган',

    'date' => 'Сана',
    'Delete' => 'Ўчириш',
    'description' => 'Изох',
    'details' => 'Тўла кўриш',
    'difficulty' => 'Даражаси',

    'exam' => 'Имтохон',
    'email' => 'Электрон манзил',

    'faculty' => 'Факультет',
    'finished_at' => 'Тугаган вақт',
    'forbidden' => 'Ушбу амални бажариш учун рухсатингиз йўқ !!!',
    'fullname' => 'ФИО',

    'gruppa' => 'Гурух',

    'home' => 'Бош саҳифа',

    'id' => '№',
    'is_correct' => 'Тўғри',
    'lang' => 'тил',
    'lecture' => 'Маъруза матни',
    'resource' => 'Адабиётлар',
    'resource-files' => 'Адабиётлар файл кўринишда',

    'media' => 'Мулти медиа',
    'multianswer' => 'Кўп жавобли',

    'name' => 'номи',
    'not-enough' => 'Етарлича маълумот мавжуд эмас',
    'not-found' => 'Ушбу манба топилмади',

    'password' => 'Пароль',
    'phone' => 'Телефон',
    'placeholder-address' => 'Манзилни киритинг',
    'placeholder-birthplace' => 'Туғилган манзилни киритинг',
    'placeholder-course' => 'Курсни танланг',
    'placeholder-email' => 'Emailни киритинг',
    'placeholder-fullname' => 'ФИОни киритинг',
    'placeholder-gruppa' => 'Гурухни киритинг',
    'placeholder-password' => 'Паролни киритинг',
    'placeholder-phone' => 'Телефон рақамини киритинг',
    'placeholder-username' => 'Логинни киритинг',

    'question' => 'Савол',
    'questions' => 'Тест саволлари',
    'essies' => 'Саволлар',
    'task' => 'Зиддиятли масала',
    'tasks' => 'Зиддиятли масалалар',
    'total' => 'Жами',
	
    'test-summary' => 'Жами балл: <span class="label label-primary">{total}</span> тўғри: <span class="label label-success">{success}</span> нотўғри: <span class="label label-danger">{fail}</span>',

    'rating' => 'Бахоси',
    'remember-me' => 'Эслаб қолиш',
    'register' => 'Журнал',

    'Reset' => '',
    'resources' => 'Адабиётлар',

    'Search' => 'Қидириш',
    'sequence' => 'Дарс номери',
    'started_at' => 'Бошланган вақт',
    'status' => 'Холати',
    'students' => 'Талабалар',

    'test' => 'Тест натижалари',
    'time_difference' => 'Сарфланган вақт',
    'title' => 'Мавзу',
    'type' => 'тури',

    'Update {modelClass}: ' => '{modelClass} ни ўзгартириш',
    'Update' => 'Ўзгартириш',
    'updated_at' => 'Ўзгартирилган',
    'user' => 'фойдаланувчи',
    'username' => 'Логин',
    'users' => 'фойдаланувчилар',

    'subject' => 'Фан',
    'short-name' => 'Қисқа номи',
    'subjects' => 'Фанлар',
    'kafedra' => 'Кафедра',
    'kafedras' => 'Кафедралар',
    'Active' => 'Фаол',
    'Not active' => 'Но фаол',
    'kafedras and subjects' => 'Кафедра ва фанлар',
];
