<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action'=>'Amallar',
    'address' => 'Manzil',
    'answer' => 'Javob',
    'answers' => 'Javoblar',
    'Are you sure you want to delete this item?' => 'Ushbu yozuvni o\'chirishga aminmisiz?',
    'article' => 'dars',
    'articles' => 'Darslar',
    'author' => 'Muallif',

    'birthplace' => 'Tug\'ilgan manzil',
    'btn-create' => '<i class="fa fa-plus"></i> Qo\'shish',
    'btn-delete' => '<i class="fa fa-trash-o"></i> O\'chirish',
    'btn-exam' => '<i class="fa fa-question-circle"></i> Test',
    'btn-next' => '<i class="fa fa-play-circle"></i> Keyingisi',
    'btn-save' => '<i class="fa fa-floppy-o"></i> Saqlash',
    'btn-sign-in' => 'Kirish',
    'btn-sign-out' => 'Chiqish',
    'btn-update' => '<i class="fa fa-pencil"></i> Tahrirlash',

    'btn-question' => '<i class="fa fa-question"></i> Savollar',
    'btn-rate' => '<i class="fa fa-pencil-square"></i> Baholash',
    'btn-search' => '<i class="fa fa-binoculars"></i> Qidiruv',
    'btn-add' => '<i class="fa fa-plus-circle"></i> Qo\'shish',
    'behaviors' => 'Qo\'shimcha',


    'comment' => 'Izoh',
    'confirm' => 'Tasdiq',
    'confirm-delete' => 'Ushbu yozuvni o\'chirishga aminmisiz?',
    'contact' => 'Bog\'lanish',
    'course' => 'Kurs',
    'courses' => 'Kurslar',
    'Create' => 'Yangi',
    'created_at' => 'Yaratilgan vaqt',
    'created_by' => 'Tomonidan yaratilgan yoki o\'zgartirilgan',

    'date' => 'Sana',
    'Delete' => 'O\'chirish',
    'description' => 'Izoh',
    'details' => 'To\'la ko\'rish',
    'difficulty' => 'Darajasi',

    'exam' => 'Imtixon',
    'email' => 'Elektron manzil',

    'faculty' => 'Fakultet',
    'finished_at' => 'Tug\'ilgan vaqt',
    'forbidden' => 'Ushbu amalni bajarishga ruhsatingiz yo\'q !!!',
    'fullname' => 'FIO',

    'gruppa' => 'Guruh',

    'home' => 'Bosh sahifa',

    'id' => '#',
    'is_correct' => 'To\'g\'ri',
    'lang' => 'til',
    'lecture' => 'Maru\'za matni',
    'resource' => 'Adabiyotlar',

    'media' => 'Multi media',
    'multianswer' => 'Ko\'p javobli',

    'name' => 'nomi',
    'not-enough' => 'Yetarlicha ma\'lumot mavjud emas',
    'not-found' => 'Ushbu manbaa topilmadi',

    'password' => 'kalit so\'z',
    'phone' => 'Telefon',
    'placeholder-address' => 'Manzilni kiriting',
    'placeholder-birthplace' => 'Tug\'ilgan manzilni kiriting',
    'placeholder-course' => 'Kursni kiriting',
    'placeholder-email' => 'Emailni kiriting',
    'placeholder-fullname' => 'FIOni kiriting',
    'placeholder-gruppa' => 'Guruhni kiriting',
    'placeholder-password' => 'Parolni kiriting',
    'placeholder-phone' => 'Telefon raqamini kiriting',
    'placeholder-username' => 'Loginni kiriting',

    'question' => 'Savol',
    'questions' => 'Test savollari',
    'essies' => 'Savollar',
    'task' => 'Ziddiyatli masala',
    'tasks' => 'Ziddiyatli masalalar',
    'total' => 'Jami',
    'test-summary' => 'Jami ball: <span class="label label-primary">{total}</span>   to\'g\'ri: <span class="label label-success">{success}</span>  noto\'g\'ri: <span class="label label-danger">{fail}</span>',

    'rating' => 'Baxosi',
    'remember-me' => 'Eslab qolish',
    'register' => 'Jurnal',

    'Reset' => '',
    'resources' => 'Adabiyotlar',

    'Search' => 'Qidirish',
    'sequence' => 'Dars nomeri',
    'started_at' => 'Boshlangan vaqt',
    'status' => 'Xolati',
    'students' => 'Talabalar',

    'test' => 'Test natijalari',
    'time_difference' => 'Sarflangan vaqt',
    'title' => 'Mavzu',
    'type' => 'turi',

    'Update {modelClass}: ' => '{modelClass} ni o\'zgartirish',
    'Update' => 'O\'zgartirish',
    'updated_at' => 'O\'zgartirilgan',
    'user' => 'foydalanuvchi',
    'username' => 'Login',
    'users' => 'foydalanuvchilar',

    'subject' => 'Fan',
    'short-name' => 'Qisqa nomi',
    'subjects' => 'Fanlar',
    'kafedra' => 'Kafedra',
    'kafedras' => 'Kafedralar',
    'Active' => 'Faol',
    'Not active' => 'Nofaol',
    'kafedras and subjects' => 'Kafedra va fanlar',
];
