<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
//    'address' => 'address',
//    'answer' => 'answer',
//    'answers' => 'answers',
//    'Are you sure you want to delete this item?' => 'Are you sure you want to delete this item?' ,
//    'article' => 'article',
//    'articles' => 'articles',
//    'author' => 'author',

    'birthplace' => 'Birthplace',
    'btn-create' => '<i class="fa fa-plus"></i> Create',
    'btn-delete' => '<i class="fa fa-trash-o"></i> Delete',
    'btn-exam' => '<i class="fa fa-question-circle"></i> Exam',
    'btn-next' => '<i class="fa fa-play-circle"></i> Next',
    'btn-save' => '<i class="fa fa-floppy-o"></i> Save',
    'btn-sign-in' => 'Sign in',
    'btn-sign-out' => 'Sign out',
    'btn-update' => '<i class="fa fa-pencil"></i> Update',
    'btn-question' => '<i class="fa fa-question"></i> Questions',
    'btn-rate' => '<i class="fa fa-pencil-square"></i> Rate',
    'btn-search' => '<i class="fa fa-binoculars"></i> Search',
    'btn-add' => '<i class="fa fa-plus-circle"></i> Add',
    'behaviors' => 'Additional',

    'comment' => 'Comment',
    'confirm' => 'Confirm',
    'confirm-delete' => 'Are you sure to delete this record?',
    'contact' => 'Contact',
    'course' => 'Course',
    'courses' => 'Courses',
    'Create' => 'Create',
    'created_at' => 'Created time',
    'created_by' => 'Last updated by ',

    'Delete' => 'Delete',
    'description' => 'Description',
    'details' => 'Detailed information',
//    'difficulty' => 'Darajasi',

//    'exam' => 'Imtixon',
//    'email' => 'Elektron manzil',
//
    'faculty' => 'Faculty',
    'finished_at' => 'finished time',
    'forbidden' => 'You don\'nt have enough permission to this action !!!',
    'fullname' => 'Fullname',

    'gruppa' => 'Group',

    'home' => 'Home page',

    'id' => '#',
    'is_correct' => 'Correct',
    'lang' => 'language',
    'lecture' => 'Lecture',
    'resource' => 'Resources',
    'resource-files' => 'Resources with file',

    'media' => 'Multi media',
//    'multianswer' => 'Ko\'p javobli',

//    'name' => 'nomi',
    'not-enough' => 'Not enough information',
    'not-found' => 'Resources not found',

//    'password' => 'kalit so\'z',
    'phone' => 'Phone number',
    'placeholder-address' => 'Please enter the address',
    'placeholder-birthplace' => 'Please enter the birthplace',
    'placeholder-course' => 'Please enter course',
    'placeholder-email' => 'Please enter the email',
    'placeholder-fullname' =>'Please enter fullname',
    'placeholder-gruppa' => 'Please enter group',
    'placeholder-password' => 'Please enter password',
    'placeholder-phone' => 'Please enter phone',
    'placeholder-username' => 'Please enter username',

    'question' => 'Question',
    'questions' => 'Test questions',

    'essies' => 'Questions',
    'task' => 'Task',
    'tasks' => 'Situational task',
    'test-summary' => 'Total: <span class="label label-primary">{total}</span> success: <span class="label label-success">{success}</span> fail: <span class="label label-danger">{fail}</span>',
//
    'rating' => 'Assesment',
    'remember-me' => 'Remember me',
    'register' => 'Register book',
//    'Reset' => '',
//    'resources' => 'Adabiyotlar',
//
//    'Search' => '',
    'sequence' => 'Lesson Number',
    'started_at' => 'Started at ',
    'status' => 'Status',
//    'students' => 'Talabalar',

    'test' => 'Test results',
    'time_difference' => 'Time difference',
//    'title' => 'Mavzu',
//    'total' => 'Jami',
//    'type' => 'turi',

    'Update {modelClass}: ' => 'Update {modelClass}:',
//    'Update' => 'O\'zgartirish',
    'updated_at' => 'Updated time',
//    'user' => 'foydalanuvchi',
    'username' => 'Login',

    'short-name' => 'Short name',
    'kafedra' => 'Lectern',
    'kafedras' => 'Lecterns',
    'kafedras and subjects' => 'Kafedra va fanlar',
];
